### PR TITLE
modify syntax for ruby 3.x compatibility

### PR DESCRIPTION
**Pull request by modullar**

### CODE REVIEW

**Comment by arthurhess** [comment]
Thanks, I came here for this. This project looks abandoned, though.

**Comment by modullar** [comment]
@arthurhess 
It's into the oblivion, and the intention to make the changes backward compatible, but that would more tedious, so this is just a workaround if you clone the gem and used it locally

**Comment by joonty** [comment]
@arthurhess got in touch by email and asked me whether he could help maintain this repo. Although life got in the way, I also had the issue of not receiving emails from this repo specifically, so I wasn't aware of the open issues and PRs.

@arthurhess is joining to help out. Let's get this show back on the road!

**Comment by joonty** [comment]
This has been resolved and included in the v0.5.0 release. Thank you for your PR, and apologies for the delay!

**Pull request closed without merging**
