### PR TITLE
Fixes #15 - Support inline comments

### LINKED ISSUE #15: Parser stops after comment
We use comments to label gems in our Gemfile (sometimes the use of a gem doesn't come easily from the name :smile:) and this seems to stop the Pessimize parser from labeling subsequent gem lines. I've attached a sample Gemfile (and the Gemfile.backup) that triggers the issue. If I remove the ruby comment everything seems to work great.

Gemfile (after running `pessimize`):

``` ruby
# A sample Gemfile
source "https://rubygems.org"

gem "rails", "~> 4.2"
gem "pessimize", "~> 0.3" # Breaks here
gem "devise"
```

Gemfile.backup:

``` ruby
# A sample Gemfile
source "https://rubygems.org"

gem "rails"
gem "pessimize" # Breaks here
gem "devise"
```

### PR DESCRIPTION
**Pull request by randallreedjr**
This pull request implements fixes for three issues:

Issue #15 - Continue parsing after a line with an inline comment (@bsedat's fix), now with a passing build
Issue #19 - Replace link with updated documentation
Issue #21 - Set `codeclimate-test-reporter` version in Gemfile to avoid breaking changes in 1.0.0

### CODE REVIEW

**Comment by randallreedjr** [comment]
@joonty I would love to get this merged in as soon as possible! Please let me know if I missed anything regarding contribution guidelines.

**Comment by randallreedjr** [comment]
@joonty Anything I can do to help get this merged in? Thanks!

**Comment by randallreedjr** [comment]
@joonty Just a reminder to check out this pull request. :)

**Comment by jleo3** [comment]
:100: I would love to see this change incorporated into the next release!

**Comment by taylorthurlow** [comment]
I too would like to see this merged.

I'm not sure if it's my inexperience showing or not, but I couldn't for the life of me figure out how to clone this repo with this pull request and use it on my gemfile, so I forked the gem and applied this patch. Repo is [here](https://github.com/taylorthurlow/pessimize).

**Comment by randallreedjr** [comment]
@joonty I'd be happy to help manage this repo. Would you be open to adding me as a collaborator?

**Comment by joonty** [comment]
Sorry everyone. Life (kids!) has taken over a bit!

I'm going to block in some time to work on pessimize, so I'll check this over properly. Sorry for the long wait.

**Comment by randallreedjr** [comment]
@joonty No worries! We all know how that goes.

**Comment by joonty** [comment]
Thanks @randallreedjr and @bsedat for your work! I've tried this out and it all works well. I'll get this version released to rubygems.org.

**Pull request merged**
